CREATE TABLE CUSTOMER_REGISTRATION(
 ACCNO INT Identity(100000000,1) PRIMARY KEY,
 NAME VARCHAR(50),
 MOB_NO VARCHAR(10),
 AGE INT,
 EMAIL VARCHAR(50),
 BALANCE FLOAT,
 AADHAR INT,
)
// CONSTRAINT CHK_MO CHECK(MOB_NO NOT LIKE '%[^0-9]%'
)
DROP TABLE CUSTOMER_REGISTRATION

SELECT * FROM CUSTOMER_REGISTRATION

DROP PROCEDURE INSERT_CUSTOMER


INSERT INTO CUSTOMER_REGISTRATION VALUES('UMESH','1234554321',21,'NAGPUR',1000,'VAIDYAUMESH36@GMAIL.COM')
INSERT INTO CUSTOMER_REGISTRATION VALUES('SHIFA','9999999999',21,'ABC',500,'SHIFA@GMAIL.COM')

SELECT * FROM CUSTOMER_REGISTRATION


CREATE PROCEDURE INSERT_CUSTOMER
@NAME VARCHAR(50),
@MOB_NO CHAR(10),
@AGE INT,
@EMAIL VARCHAR(50),
@BALANCE FLOAT,
@AADHAR INT
AS
	BEGIN
	INSERT INTO CUSTOMER_REGISTRATION(NAME,MOB_NO,AGE,EMAIL,BALANCE,AADHAR)
	VALUES(@NAME,@MOB_NO,@AGE,@EMAIL,@BALANCE,@AADHAR)
	END
GO

EXEC INSERT_CUSTOMER 'SAYALI','14525555556',22,'SAYALI@GMAIL.COM',5600,14526;



CREATE PROCEDURE VIEWBALANCE
@ACCNO INT
AS
	BEGIN
	IF EXISTS(SELECT ACCNO FROM CUSTOMER_REGISTRATION WHERE ACCNO = @ACCNO)
	SELECT ACCNO,NAME,MOB_NO,AGE,BALANCE FROM CUSTOMER_REGISTRATION WHERE ACCNO = @ACCNO;
	END
GO

exec VIEWBALANCE 100000000

drop procedure VIEWBALANCE


CREATE PROCEDURE ENTER_ACCNO
@ACCNO INT
AS
BEGIN 
	INSERT INTO CUSTOMER_REGISTRATION(ACCNO) VALUES(@ACCNO) 
END 


CREATE PROCEDURE VIEWMANAGER
AS
BEGIN 
SELECT * FROM CUSTOMER_REGISTRATION
END
GO
EXEC VIEWMANAGER