CREATE TABLE LOGIN(
 SRNO INT Identity(1,1),
 USERNAME VARCHAR(50) UNIQUE,
 USERPASSWORD VARCHAR(50),
 ROLID INT)

 SELECT * FROM LOGIN;
CREATE PROCEDURE LOGIN_METHOD
(@USERNAME  VARCHAR(50),@USERPASSWORD  VARCHAR(50))
AS BEGIN
SELECT USERNAME,
ROLID FROM LOGIN WHERE 
USERNAME= @USERNAME AND USERPASSWORD=@USERPASSWORD
END;
