
CREATE TABLE CUST_TRANSACTION(
 TRANSACTION_ID INT Identity(800000,1) not null PRIMARY KEY,
 ACCNO INT NOT NULL FOREIGN KEY REFERENCES CUSTOMER_REGISTRATION(ACCNO),
 TO_ACCNO INT NOT NULL FOREIGN KEY REFERENCES CUSTOMER_REGISTRATION(ACCNO),
  SYS_DATE DATE DEFAULT GETDATE(),
  TRANSACTIONTYPE VARCHAR(10),
  AMOUNT FLOAT DEFAULT 0
)
INSERT INTO CUST_TRANSACTION VALUES(100000000,100000001,DEFAULT,'TRANSFER',1000)

DROP TABLE CUST_TRANSACTION
SELECT * FROM CUST_TRANSACTION
SELECT TO_ACCNO FROM CUST_TRANSACTION

DROP TABLE CUSTOMER_REGISTRATION

CREATE PROCEDURE TRANSFERMONEY
@ACCNO INT,
@TO_ACCNO INT,
@TRANSACTIONTYPE VARCHAR(10),
@AMOUNT FLOAT
AS  
BEGIN
DECLARE @DESTACC_NO INT;
SET @DESTACC_NO = @TO_ACCNO;
IF ((SELECT BALANCE FROM CUSTOMER_REGISTRATION WHERE @ACCNO=ACCNO)>@AMOUNT)
BEGIN
INSERT INTO CUST_TRANSACTION(ACCNO,TO_ACCNO,SYS_DATE,TRANSACTIONTYPE,AMOUNT)
	VALUES(@ACCNO,@TO_ACCNO,DEFAULT,@TRANSACTIONTYPE,@AMOUNT)
UPDATE CUSTOMER_REGISTRATION
SET BALANCE = BALANCE-@AMOUNT WHERE ACCNO=@ACCNO 
UPDATE CUSTOMER_REGISTRATION
SET BALANCE = BALANCE+@AMOUNT WHERE ACCNO=@DESTACC_NO 
UPDATE CUST_TRANSACTION
SET TRANSACTIONTYPE = 'CREDIT' WHERE ACCNO=@DESTACC_NO 
END
END
GO

EXEC  TRANSFERMONEY 100000001,100000000,'TRANSFER',5000;
EXEC  TRANSFERMONEY 100000001,500.0,100000000;



DROP PROCEDURE TRANSFERMONEY




CREATE PROCEDURE INSERT_CUSTOMER
@NAME VARCHAR(20),
@AGE INT,
@BRANCH_NAME  VARCHAR(50),
@EMAIL VARCHAR(50)
AS
	BEGIN
	INSERT INTO CUSTOMER_REGISTRATION(NAME,AGE,BRANCH_NAME,EMAIL)
	VALUES(@NAME,@AGE,@BRANCH_NAME,@EMAIL)
	END
GO

DROP PROCEDURE TRANSFERMONEY



CREATE PROCEDURE VIEWMINISTATEMENT
AS
	BEGIN
	SELECT * FROM CUST_TRANSACTION
	END
GO

EXEC																																																																										
